"""active column for File

Revision ID: 2c9b3a85879d
Revises: 0268bdc69c35
Create Date: 2024-08-19 16:11:05.135323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9b3a85879d'
down_revision: Union[str, None] = '0268bdc69c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'active')
    # ### end Alembic commands ###
